name: Build and test

on:
  push:
    branches-ignore:
      - v2
      - gh-pages

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          context: src
          push: false
          outputs: type=local,dest=lib
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - run: |
          yarn install
          test -f lib/module.mjs && touch lib/module.mjs
          test -f lib/module.wasm && touch lib/module.wasm
          make

      - uses: actions/upload-artifact@v3
        with:
          name: lib
          path: lib

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: lib
          path: lib

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - run: yarn install && yarn test
