name: Build and test

on:
  push:
    branches-ignore:
      - v2
      - gh-pages
  workflow_call: {}

permissions:
  contents: read

jobs:
  lang-dot-test:
    name: Build and test lang-dot package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: "Run build and test"
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test
        working-directory: packages/lang-dot

  viz-build:
    name: Build viz package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          context: packages/viz/src/module
          push: false
          outputs: type=local,dest=packages/viz/lib
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: "Build"
        run: |
          yarn install --frozen-lockfile
          test -f lib/module.mjs && touch lib/module.mjs
          test -f lib/module.wasm && touch lib/module.wasm
          make
        working-directory: packages/viz

      - uses: actions/upload-artifact@v3
        with:
          name: lib
          path: packages/viz/lib

  viz-test:
    name: Test viz package
    needs: viz-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: lib
          path: packages/viz/lib

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: "Run tests"
        run: |
          yarn install --frozen-lockfile
          yarn test
        working-directory: packages/viz

  viz-test-consume:
    name: Test import and require for viz package
    needs: viz-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: lib
          path: packages/viz/lib

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: "Run module-import test"
        run: |
          yarn install --frozen-lockfile
          node index.js
        working-directory: packages/viz/test/module-import

      - name: "Run commonjs-require test"
        run: |
          yarn install --frozen-lockfile
          node index.js
        working-directory: packages/viz/test/commonjs-require

  viz-test-types:
    name: Test types for viz package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: "Run check-types"
        run: |
          yarn install --frozen-lockfile
          yarn check-types
        working-directory: packages/viz/test/types
