name: Publish release and NPM package

on:
  push:
    tags: ["v*"]

jobs:
  build:
    uses: ./.github/workflows/build-docker.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: lib
          path: lib

      - run: gh release create ${{ github.ref }} lib/*
        env:
          GH_TOKEN: ${{ github.token }}

  publish:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: lib
          path: lib

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm install -g npm

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
